name: CI


# this is triggered on push to the repository
on: [push, pull_request]

env: 
  CODECOV_TOKEN:80d7d11d-0f37-437e-8cad-de3e7b624191

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Coverage Tool
      run: go get golang.org/x/tools/cmd/cover
    - name: Test
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
    - name: Push Coverage to codecov.io
      run: bash <(curl -s https://codecov.io/bash)